name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      id: ssh-setup
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        ssh-keyscan -H ec2-3-109-123-52.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH and deploy
      run: |
        ssh -i keyfile ubuntu@ec2-3-109-123-52.ap-south-1.compute.amazonaws.com "source ~/deploy.sh"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
